import type { StyleLibraryLabels } from "@human2ai/ui";
import type { TFunction } from "i18next";

export function getStyleLibraryLabels(t: TFunction): StyleLibraryLabels {
  return {
    newStyle: t("styleLibrary.newStyle"),
    editStyle: t("styleLibrary.editStyle"),
    name: t("styleLibrary.name"),
    namePlaceholder: t("styleLibrary.namePlaceholder"),
    category: t("styleLibrary.category.label"),
    allCategories: t("styleLibrary.category.all"),
    visualCategory: t("styleLibrary.category.visual"),
    uiCategory: t("styleLibrary.category.ui"),
    creator: t("styleLibrary.creator.label"),
    allCreators: t("styleLibrary.creator.all"),
    userCreator: t("styleLibrary.creator.user"),
    agentCreator: t("styleLibrary.creator.agent"),
    references: t("styleLibrary.references.heading"),
    noReferences: t("styleLibrary.references.empty"),
    addReferences: t("styleLibrary.references.add"),
    removeReference: t("styleLibrary.references.remove"),
    pasteHint: t("styleLibrary.references.pasteHint"),
    fileTypes: t("styleLibrary.references.fileTypes"),
    description: t("styleLibrary.description.heading"),
    promptSummary: t("styleLibrary.promptSummary.label"),
    promptSummaryPlaceholder: t("styleLibrary.promptSummary.placeholder"),
    descriptionPlaceholder: t("styleLibrary.description.placeholder"),
    searchPlaceholder: t("styleLibrary.searchPlaceholder"),
    deleteTitle: t("styleLibrary.deleteTitle"),
    deleteDescription: t("styleLibrary.deleteDescription"),
    empty: t("styleLibrary.empty"),
    noMatches: t("styleLibrary.noMatches"),
    loading: t("styleLibrary.loading"),
    loadFailed: t("styleLibrary.loadFailed"),
    retry: t("actions.retry"),
    save: t("styleLibrary.save"),
    cancel: t("actions.cancel"),
    delete: t("actions.delete"),
    operationFailed: t("errors.operationFailed"),
    imageInvalid: t("styleLibrary.imageInvalid"),
    openStyle: (name) => t("styleLibrary.openStyle", { name }),
    closePreview: t("styleLibrary.closePreview"),
  };
}
