import type { StyleEntry } from "../../../../../src/domain/style";
import type { StyleLibraryLabels } from "./StyleLibraryView";

export const image = "data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1200' height='800'%3E%3Crect width='1200' height='800' fill='%23e7e2da'/%3E%3Ccircle cx='410' cy='400' r='190' fill='%23272b30'/%3E%3Crect x='650' y='180' width='330' height='440' rx='28' fill='%23faf8f3'/%3E%3C/svg%3E";

export const labels: StyleLibraryLabels = {
  model: {
    label: "模型示例", loading: "正在加载模型", failed: "模型无法预览", reset: "重置模型视角",
    controls: "拖动旋转，滚轮缩放；聚焦后用方向键旋转，+ / − 缩放，Home 重置。", retry: "重试",
  },
  newStyle: "新建风格",
  editStyle: "编辑风格",
  name: "名称",
  namePlaceholder: "输入风格名称",
  category: "分类",
  allCategories: "全部类型",
  visualCategory: "画面",
  uiCategory: "UI",
  spatialCategory: "3D",
  creator: "创建方",
  allCreators: "全部创建方",
  userCreator: "User",
  agentCreator: "Agent",
  references: "参考",
  noReferences: "无参考图",
  addReferences: "添加参考图",
  removeReference: "删除参考图",
  pasteHint: "在此粘贴图片，或选择本地图片。",
  fileTypes: "参考图支持 PNG、JPEG、WebP，最大 10 MB。",
  description: "设计规范",
  promptSummary: "风格短句",
  promptSummaryPlaceholder: "用一句话概括最鲜明的视觉特征",
  descriptionPlaceholder: "说明布局、比例、视觉层级和装饰等设计规则",
  spatialDescriptionPlaceholder: "说明形体、比例、材质、配色、光照和镜头等建模规则",
  searchPlaceholder: "搜索风格",
  deleteTitle: "确认删除这个风格？",
  deleteDescription: "该风格及其全部参考图和模型将被永久删除。",
  empty: "还没有风格",
  noMatches: "没有匹配的风格",
  loading: "正在加载风格",
  loadFailed: "风格加载失败",
  retry: "重试",
  save: "保存",
  cancel: "取消",
  delete: "删除",
  operationFailed: "操作失败，请重试。",
  imageInvalid: "请选择不超过 10 MB 的有效 PNG、JPEG 或 WebP 图片。",
  openStyle: (name) => `打开“${name}”`,
  closePreview: "关闭风格预览",
};

export const fixtureStyles: StyleEntry[] = [
  {
    id: "visual-1",
    name: "低饱和电影感",
    category: "visual",
    creatorType: "user",
    description: "压低整体饱和度，以冷灰和自然材质构成安静、克制的画面。主体保持明确，但避免过强的局部锐化与戏剧化光效。",
    promptSummary: "低饱和冷灰色调，主体明确，光效克制。",
    referenceImages: [
      {
        id: "reference-1",
        styleId: "visual-1",
        originalFilename: "cinematic.png",
        mimeType: "image/png",
        byteSize: 1024,
        width: 1200,
        height: 800,
        position: 0,
        createdAt: "2026-09-03T10:00:00.000Z",
      },
      {
        id: "reference-2",
        styleId: "visual-1",
        originalFilename: "cinematic-detail.png",
        mimeType: "image/png",
        byteSize: 1024,
        width: 1200,
        height: 800,
        position: 1,
        createdAt: "2026-09-03T10:01:00.000Z",
      },
    ],
    revision: 3,
    createdAt: "2026-09-03T10:00:00.000Z",
    updatedAt: "2026-09-03T10:01:00.000Z",
  },
  {
    id: "ui-1",
    name: "克制型工作台",
    category: "ui",
    creatorType: "agent",
    description: "不依赖层层卡片表达结构。页面只保留清晰外边界，内部通过留白、字重、对齐和少量色彩建立信息层级。",
    promptSummary: "大幅留白，以字重、对齐和少量色彩组织层级。",
    referenceImages: [],
    revision: 1,
    createdAt: "2026-09-03T11:00:00.000Z",
    updatedAt: "2026-09-03T11:00:00.000Z",
  },
  {
    id: "spatial-1", name: "低多边形玩具城市", category: "spatial", creatorType: "agent",
    description: "使用简洁块面与圆润轮廓，建筑略矮胖，门窗适度夸张。采用哑光材质、奶油白主体和少量蓝绿点缀，柔和阴影。按空间草稿保留指定的布局、尺度关系和相机视角。",
    promptSummary: "圆润低多边形，哑光奶油白与低饱和蓝绿，柔和阴影。",
    referenceImages: [], revision: 1,
    createdAt: "2026-09-19T10:00:00.000Z", updatedAt: "2026-09-19T10:00:00.000Z",
  },
];
